
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kanban
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: kanban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers: 
      - name: notification
        image: walymb/notification:latest
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
        env:
        - name: JWK_SET_URI
          value: http://kanban-service:9090/.well-known/jwks.json
        - name: CORS_ORIGINS
          value: "*"
        - name: FIREBASE_CONFIG_FILE
          value: "/app/keys/firebase.json"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: DB_HOST
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "notification"
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: CLIENT_SECRET
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keys-volume
          mountPath: /app/keys
      volumes:
      - name: keys-volume
        persistentVolumeClaim:
          claimName: keys-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: kanban
spec:
  selector:
    app: notification
  ports:
  - port: 9092
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-ingress
  namespace: kanban
  labels:
    name: notification-ingress
spec:
  rules:
  - host: notification.rancher.waly.dev.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: notification-service
            port: 
              number: 9092


