apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keys-pvc
  namespace: kanban
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: app-longhorn
  resources:
    requests:
      storage: 1Gi

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kanban-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kanban
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban
  namespace: kanban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban
  template:
    metadata:
      labels:
        app: kanban
    spec:
      containers: 
      - name: kanban
        image: walymb/kanbanapp:latest
        resources:
          limits:
            memory: "600Mi"
            cpu: "700m"
        env:
        - name: CORS_ORIGINS
          value: "*"
        - name: PRIVATE_KEY_PATH
          value: "/app/keys/"
        - name: JWT_DURATION
          value: "604800"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: DB_HOST
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "kanban"
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: CLIENT_SECRET
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: GITHUB_CLIENT_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: GOOGLE_CLIENT_SECRET
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: DB_PASSWORD
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: AWS_SECRET
        - name: DSCATALOG_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: kanban-secret
              key: DSCATALOG_BUCKET_NAME
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keys-volume
          mountPath: /app/keys
      volumes:
      - name: keys-volume
        persistentVolumeClaim:
          claimName: keys-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: kanban-service
  namespace: kanban
spec:
  selector:
    app: kanban
  ports:
  - port: 9090
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanban-ingress
  namespace: kanban
  labels:
    name: kanban-ingress
spec:
  rules:
  - host: kanban.rancher.waly.dev.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kanban-service
            port: 
              number: 9090


