
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: kanban
type: Opaque
data:
  CLIENT_ID: bXljbGllbnRpZA==
  CLIENT_SECRET: bXljbGllbnRzZWNyZXQ=
  DB_HOST: MzQuMTYuMTgxLjEzMg==
  DB_USERNAME: d2FseQ==
  DB_PASSWORD: MjIyMTM0Mg==
  KAFKA_BOOTSTRAP_SERVERS: MzQuMTYuMTgxLjEzMjo5MDky



